on:
  push:
    branches:
      - dbup-integration
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            clean: false

      - name: Install dbops module
        run: pwsh -Command "Install-Module dbops -Force"

      - name: Deploy
        shell: pwsh
        env:
          ConnectionString: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          cd C:\actions-runner\_work\FELL-CART\FELL-CART\CartApi
          Install-DBOPackage Migration.zip -Variables @{ connectionString = $env:ConnectionString }
          dotnet publish -c Release -o .\app
          Remove-Item -Recurse -Force -Exclude appsettings.json C:\inetpub\wwwroot\cart-api\*
          Copy-Item -Recurse -Force -Exclude appsettings.json .\app\* C:\inetpub\wwwroot\cart-api\
          cd ..
          git checkout HEAD

