on:
  push:
    branches:
      - dbup-integration
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dbops module
        run: pwsh -Command "Install-Module dbops -Force"
      - name: Deploy
        shell: pwsh
        env:
          ConnectionString: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          powershell
          cd C:\actions-runner\_work\FELL-CART\FELL-CART\CartAPI
          Install-DBOPackage Migration.zip -Variables @{ connectionString = $env:ConnectionString }
          dotnet publish -c Release -o C:\inetpub\wwwroot\cart-api