on:
  push:
    branches:
      - dbup-integration
jobs:
  deploy:
    runs-on: windows-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.1.x"

      - name: Publish app
        run: dotnet publish -c Release -o publish

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ./publish
          target: 'C:\inetpub\wwwroot\cart-api'

      - name: Execute PowerShell script
        uses: microsoft/powershell@v1
        with:
          pwsh: true
          inlineScript: |
            $connectionString = ${{ secrets.DB_CONNECTION_STRING }}
            cd C:\inetpub\wwwroot\cart-api
            Install-DBOPackage Migration.zip -Variables @{ connectionString = $connectionString }
