on:
  push:
    branches:
      - dbup-integration
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish
        run: dotnet publish -c Release -o C:\actions-runner\_work\FELL-CART\FELL-CART\app
      - name: Check module
        run: pwsh -Command "Get-Module dbops"
      - name: Install dbops module
        run: pwsh -Command "Install-Module dbops -Force"
      - name: Deploy
        shell: pwsh
        env:
          ConnectionString: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          powershell
          cd C:\actions-runner\_work\FELL-CART\FELL-CART\app
          Install-DBOPackage Migration.zip -Variables @{ connectionString = $env:ConnectionString }
          cd C:\inetpub\wwwroot\cart-api
          Remove-Item -Recurse -Force -Exclude appsettings.json *
          Copy-Item -Recurse -Force -Exclude appsettings.json C:\actions-runner\_work\FELL-CART\FELL-CART\app\* .
          Remove-Item -Recurse -Force -Exclude appsettings.json C:\actions-runner\_work\*
