on:
  push:
    branches:
      - dbup-integration
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 5.0

      - name: Build
        run: dotnet build --configuration Release .\cart-api-build

      - name: Publish
        run: |
            dotnet publish -c Release -o cart-api-publish .\cart-api-build

      - name: Deploy
        shell: pwsh
        env:
          ConnectionString: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          Stop-WebAppPool -Name "cart-api"
          Copy-Item -Recurse -Force -Exclude appsettings.json .\app\* C:\inetpub\wwwroot\cart-api\
          Start-WebAppPool -Name "cart-api"
