on:
  push:
    branches:
      - dbup-integration
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Publish
      run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/app
    - name: Deploy
      env:
        ConnectionString: ${{ secrets.DB_CONNECTION_STRING }}
      run: |
        cd $(Build.ArtifactStagingDirectory)/app
        Install-DBOPackage Migration.zip -Variables @{ connectionString = $env:ConnectionString }
        cd C:\inetpub\wwwroot\cart-api
        Remove-Item -Recurse -Force -Exclude appsettings.json *
        Copy-Item -Recurse -Force -Exclude appsettings.json $(Build.ArtifactStagingDirectory)/app/* .